root = "."
tmp_dir = "tmp"

[build]
  # comando para compilar el main que está en cmd/app
  cmd = "go build -o ./tmp/main.exe ./cmd/app"
  # ruta del binario que ejecutará air
  bin = "tmp/main.exe"
  include_ext = ["go", "mod", "tmpl", "tpl"]
  exclude_dir = ["tmp", "vendor"]
